steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/registration-server:0.3.1', '.']
timeout: '1600s'
images: ['gcr.io/$PROJECT_ID/registration-server:0.3.1']
options:
  machineType: E2_HIGHCPU_8