image:
  repository: gcr.io/notes-c11be/registration-server
  pullPolicy: Always
  tag: "0.3.0"

cb:
  databaseHost: "notes-database-dev-postgresql"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: accounts-dev.codebulb.nl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: accounts-dev-codebulb-tls
     hosts:
       - accounts-dev.codebulb.nl